### ISSUE TITLE
Hover mode saving issue - dev

### ISSUE THREAD

**Issue by cycle4** [coolzhao/Geo-SAM#12]
Hello again ! 
Thanks a lot for your continuous improvements ! The new tools on the dev plugin are very useful and the next ones look very promising !
I just wanted to point out a strange behaviour of the Hover mode you may be already aware of : whenever it is enabled, saving a feature requires to disable hover mode, otherwise the saved feature is the last one prompted by the Hover mode, overwriting the segmented zone formed by the addition of a FG point. Here is a capture to better understand what I am trying to depict

https://github.com/coolzhao/Geo-SAM/assets/120014072/8265b853-2a2a-421a-b11b-4f44f453a20f

**Comment by Fanchengyan** [comment]
My previous comment was about the bug at the end of your video. Regarding your description, the hover mode currently only provides a preview for the prompt to help you make a better prompt selection. Only the prompt after clicking the mouse will be truly recorded. The bug at the end of the video seems to be triggered when no prompt is provided during saving. In addition to that, we have provided keyboard shortcuts for commonly used buttons. When you hover your mouse over a button, there will be a tooltip with text. Using keyboard shortcuts will be more convenient.

![Shortcuts in Readme](https://github.com/coolzhao/Geo-SAM/assets/24694181/f355c6c6-d4f2-4413-8202-308e0f52cdd6)

**Comment by cycle4** [comment]
Thanks for your answer ! Yes the use of shortcuts should be more convenient
