### ISSUE TITLE
Installation v1.3 dev

### ISSUE THREAD

**Issue by cycle4** [coolzhao/Geo-SAM#17]
Hell oagain !
I have a problem while installing the new dev version on my QGIS (1.28 LTR). When activating the plugin, I have the following message : 

Couldn't load plugin 'Geo-SAM' 
ModuleNotFoundError: No module named 'Geo-SAM.docs' 

I've seen that you removed the doc to make it lighter, maybe it has a link

**Comment by Fanchengyan** [comment]
Hi @cycle4 . Thank you for your feedback. We have released a new version that fixes this bug. Please feel free to give it a try.

**Comment by cycle4** [comment]
Works fine now on my side thanks !
