### ISSUE TITLE
Consider mannually adjust mask?

### ISSUE THREAD

**Issue by Li-sde** [coolzhao/Geo-SAM#4]
Hi, thank you so much for your contribution, will you consider add a option for user to manually adjust the mask?

**Comment by Fanchengyan** [comment]
Hi, @Li-sde. I am not sure whether the mask you mentioned refers to the output polygon layer (named `polygon_sam` if not specify the path of output shapefile). Actually, this layer is a shapefile layer and you can directly adjust it using QGIS, or export this layer and edit it in other GIS softwares.
