### ISSUE TITLE
download link for model checkpoints

### ISSUE THREAD

**Issue by cmosig** [coolzhao/Geo-SAM#48]
Neither the installation guide nor the encoder package doc mentions where to download the checkpoints. It used to be somewhere? Where are the checkpoints available now?

https://geo-sam.readthedocs.io/en/latest/Usage/encoder_package.html

**Comment by Fanchengyan** [comment]
Hi @cmosig 

The checkpoints available at: https://geo-sam.readthedocs.io/en/latest/Usage/encoding.html#download-sam-checkpoints

**Comment by cmosig** [comment]
Thanks! I just didn't find it... sorry.
