### ISSUE TITLE
Point is located outside of the image boundary

### ISSUE THREAD

**Issue by watchsea** [coolzhao/Geo-SAM#5]
When I add a tif to the toolset, and click the tif, pop up a message: " Point is located outside of the image boundary." I have set the crs to 4546 about tif  and the output shape file.

**Comment by ambarja** [comment]
I am with the same problem :c

**Comment by cmu002** [comment]
This issue is still persisting

**Comment by coolzhao** [comment]
Hi there, we just published a new release with the encoding tool for segmenting customized images, please take a look at the updated readme for more information.

**Comment by ambarja** [comment]
Hello everyone, I have recently opened an issue about it > https://github.com/coolzhao/Geo-SAM/issues/7#issuecomment-1655079280
